"""Lightweight Python helpers for DuckLake connections."""

from ducklake_client.client import DuckLake
from ducklake_client.config import (
    CatalogConfig,
    DiskStorage,
    DuckDBCatalog,
    DuckDBConfig,
    PostgresCatalog,
    S3Storage,
    SqliteCatalog,
    StorageConfig,
)
from ducklake_client.exceptions import (
    DuckLakeConfigError,
    DuckLakeConnectionError,
    DuckLakeError,
    DuckLakeQueryError,
)
from ducklake_client.modules import SchemaModule, SnapshotsModule, TableModule, ViewModule
from ducklake_client.schema import (
    ColumnDataType,
    ColumnDef,
    ColumnType,
    DecimalType,
    DuckLakeTableMetadata,
    ListType,
    MapType,
    SQLType,
    StructType,
    TableColumnSummary,
    TableInfo,
    TableInfoColumn,
    TableListing,
    TablePartitionSpec,
    TableSnapshotInfo,
    TableSortSpec,
    ViewListing,
)

__all__ = [
    "CatalogConfig",
    "ColumnDataType",
    "ColumnDef",
    "ColumnType",
    "DecimalType",
    "DuckDBCatalog",
    "DuckDBConfig",
    "DuckLake",
    "DuckLakeConfigError",
    "DuckLakeConnectionError",
    "DuckLakeError",
    "DuckLakeQueryError",
    "DuckLakeTableMetadata",
    "DiskStorage",
    "ListType",
    "MapType",
    "PostgresCatalog",
    "S3Storage",
    "SQLType",
    "SchemaModule",
    "SnapshotsModule",
    "SqliteCatalog",
    "StorageConfig",
    "StructType",
    "TableColumnSummary",
    "TableInfo",
    "TableInfoColumn",
    "TableListing",
    "TableModule",
    "TablePartitionSpec",
    "TableSnapshotInfo",
    "TableSortSpec",
    "ViewModule",
    "ViewListing",
]
